### ISSUE TITLE
Add direct link to the azure logic app

### ISSUE THREAD

**Issue by aleks-zhigar** [TheCatsLab/Telescope#7]
![image](https://user-images.githubusercontent.com/8442105/194861544-6aebc7fa-4fca-4f94-b296-2b4dfbeb564e.png)
like this:
![image](https://user-images.githubusercontent.com/8442105/194861743-42f0f2e4-8527-4689-acd8-754e3d26d09e.png)

**Comment by Dshauchuk** [comment]
@aleks-zhigar  Should the link lead user to the resource in Azure Portal or to itself?

**Comment by aleks-zhigar** [comment]
link should lead user to the resource in Azure Portal

**Comment by Dshauchuk** [comment]
looks like this: 
![image](https://user-images.githubusercontent.com/20374752/195675313-15bb289f-2081-41f7-b043-245c0c293e3f.png)
